version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: all_blue_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: diego
     
    ports:
      - "3307:3306" 

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
